🛠 publish on merge

diff --git a/firefox/Makefile b/firefox/Makefile
--- a/firefox/Makefile
+++ b/firefox/Makefile
@@ -1,15 +1,31 @@
-.PHONY: get-version tags
+.PHONY: get-version test publish
+
+CURRENT_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
 
 get-version:
 	@docker run --rm \
 		ubuntu:bionic \
 		sh -c "apt-get update -qq && apt-cache policy firefox | sed -En 's/.*Candidate: (.+)\+.+/\1/p'"
 
-tags:
+test:
 	@if [ -z $(version) ]; then \
 		echo "\`version\` argument is required" 1>&2; \
 		exit 1; \
 	fi
+
+	@docker build --tag firefox --build-arg VERSION=$(version) $(CURRENT_DIR)
+
+	@docker run --detach --publish 9222:9222 --name firefox firefox
+
+	@timeout 15s sh -c "trap 'docker container rm --force firefox' 0; until curl http://localhost:9222/json/version; do sleep 1; done"
+
+publish:
+	@if [ -z $(version) ]; then \
+		echo "\`version\` argument is required" 1>&2; \
+		exit 1; \
+	fi
+
+	@docker build --tag firefox --build-arg VERSION=$(version) $(CURRENT_DIR)
 
 	@for i in 1 0 -1; do \
 		if [ $$i -ge 0 ]; then \
@@ -18,7 +34,8 @@ tags:
 			tag=latest; \
 		fi; \
 		echo $$tag; \
-		tag=firefox@$$tag; \
-		git tag --force $$tag >/dev/null 2>&1; \
-		git push --force origin $$tag >/dev/null 2>&1; \
+		docker tag firefox docker.pkg.github.com/nextools/images/firefox:$$tag; \
+		docker push docker.pkg.github.com/nextools/images/firefox:$$tag; \
+		git tag --force firefox@$$tag >/dev/null 2>&1; \
+		git push --force origin firefox@$$tag >/dev/null 2>&1; \
 	done
